version: "3.8"
services:
  clio:
    entrypoint:
      [
        "/app/.venv/bin/fastapi",
        "run",
        "app/app.py",
        "--port",
        "8000",
        "--host",
        "0.0.0.0",
      ]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - couchdb
    env_file:
      - .env
  couchdb:
    image: couchdb:latest
    ports:
      - "5984:5984"
    env_file:
      - .env
    volumes:
      - couchdb-data:/opt/couchdb/data
volumes:
  couchdb-data:
